#for checking the API functions
@baseUrl = http://localhost:8000/api/v1/tasks

###GET the task list
GET {{baseUrl}}

###POST the task list
POST {{baseUrl}}

###Update the task list
PUT {{baseUrl}}

###DELETE the task list
DELETE  {{baseUrl}}