#for checking the API functions
@baseUrl = http://localhost:8000/api/v1/tasks

###GET the task list
GET {{baseUrl}}

###POST the task list
POST {{baseUrl}}
Content-Type: application/json

{
    "id":1,
    "task":"caring",
    "hr":10,
    "type": "entry"
}

###Update the task list
PATCH {{baseUrl}}
Content-Type: application/json

{
    "id":2,
    "type": "bad"
}

###DELETE the task list
DELETE  {{baseUrl}}/2